### ISSUE TITLE
Getting Askpass for every action even when its not needed

### ISSUE THREAD

**Issue by Akira-Kuru** [sourcegit-scm/sourcegit#1577]
I added ssh to the ssh-agent so I don't have to constantly add the password to the sourcegit but it keeps giving me the askpass prompt for pull, push, fetch and commits.

Even when deleting branches I also get the askpass prompt.
What I find wild with deleting branches is that if you cancel the askpass prompt, the branch gets deleted either way.

**Comment by love-linger** [comment]
<img width="343" height="182" alt="Image" src="https://github.com/user-attachments/assets/1494aeae-ff11-4a87-89e1-2c283468792c" />

This window is launched by `ssh` not `SourceGit`:

https://github.com/sourcegit-scm/sourcegit/blob/0a74dd64ce63cb4def3210291013ab50f80149d6/src/Commands/Command.cs#L167-L175

**Comment by love-linger** [comment]
I think this issue may related to #1576 

Try to download the latest CI build or compile it by yourself.

**Comment by love-linger** [comment]
Make sure you have enable the `AddKeysToAgent` configuration in `~/.ssh/config`

```
Host *
  AddKeysToAgent yes
```

**Comment by piotr-fraczek** [comment]
Hi, I have same problem, mint, manjaro. All time when I want to do some git actions - always prompt for ssh key password

```
➜  ~ cat ~/.ssh/config
Host *
  AddKeysToAgent yes
```

**Comment by love-linger** [comment]
If your private key has a passphrase, each time you use it, SSH will ask for its password. You can use `ssh-keygen -p -f <private_key>` to reset its password to empty.

**Comment by Akira-Kuru** [comment]
I added
```
Host *
  AddKeysToAgent yes
```
and the ssh-agent is running on my terminal, however I still receive the AskPass prompt. 

I even tried it out with a file creating, deleting, committing and pushing over terminal which worked without any issue.
Then the same approach with sourcegit and I still get the prompt.

Then I added this code below  in `~/.ssh/config` and attempted the same process again.

```
Host github.com
  AddKeysToAgent yes
  IdentityFile ~/.ssh/id_work
  BatchMode yes
```

This time, sourcegit decided not to commit or push and simply gave me a "Permission denied (publickey)." error even though it works on the terminal. Not giving me any prompt anymore because of  `BatchMode yes`.

I would also not take the `ssh-keygen -p -f <private_key>` approach since you are not keeping your SSH Key secure this way.

If this was an SSH issue then it would have also happened on the Terminal which it didn't.

**Comment by love-linger** [comment]
This may be because the private_key_file is passed into the SSH command every time in the code:

https://github.com/sourcegit-scm/sourcegit/blob/0a74dd64ce63cb4def3210291013ab50f80149d6/src/Commands/Command.cs#L175-L179

Later, I'll check if there is a better way to handle the SSH connection.

**Comment by love-linger** [comment]
I test this on Windows platform that when installing GIT, using external openssh (without using the built-in SSH) does not have such problems.

Makes sure `ssh-agent` service is running

<img width="1181" height="54" alt="Image" src="https://github.com/user-attachments/assets/15b4bdee-bd5b-4848-8721-5b512af63fb0" />

BTW, on which system do you encounter this problem?

**Comment by piotr-fraczek** [comment]
> BTW, on which system do you encounter this problem?

I use **Linux**: Manjaro, Mint, Ubuntu distributions

On Windows 10/11 this problem not exists :)

**Comment by Akira-Kuru** [comment]
> BTW, on which system do you encounter this problem?

I use **Linux**: Archlinux & **Windows 11**.

This happened so far only on Archlinux but I will check Windows later today.

**Comment by love-linger** [comment]
I've test this on Ubuntu. After manually add keys to `ssh-agent`, it will not ask me for passphrase any more. 


```shell
eval `ssh-agent -s` # Makes sure `ssh-agent` started
ssh-add <private_key_file> # The `<private_key_file` is the same one with `SSH Private Key` of remote configuration in `SourceGit`

# Then restart `SourceGit` and try to fetch/pull/push/create commit in `SourceGit`
```

**Comment by love-linger** [comment]
I think I know why.

- When I started `SourceGit` from the terminal session that just runs ```eval `ssh-agent -s` ```, this issue does not exists
- When I started `SourceGit` from other terminal sessions that have not ran ```eval `ssh-agent -s` ```, this issue appears

Maybe, `SSH_AGENT_PID` and `SSH_AUTH_SOCK` are needed by ssh command

**Comment by love-linger** [comment]
Fixed. When creating linux packages, a custom script (instead of symbolic link for `/opt/sourcegit/sourcegit`) has been added into `/usr/bin`. 

The content of `/usr/bin/sourcegit` is:
```shell
#!/bin/bash

eval `ssh-agent -s`
/opt/sourcegit/sourcegit $@
```

You can download the latest CI build from Github Action.

**Comment by Akira-Kuru** [comment]
> You can download the latest CI build from Github Action.

Just tried it locally and it works but I don't think I can test it out properly through the Terminal.

I just tried the develop branch and it worked but the same happened with master as well which doesn't have your changes.
I am guessing the Terminal still executes ssh-agent even after I built and adds this to sourcegit when testing locally.

**Comment by love-linger** [comment]
I will merge `develop` into `master` on next Monday.

> I don't think I can test it out properly through the Terminal.

This is not important. Because in both non-commandline mode and commandline mode, the executed file is the same one: `/usr/bin/sourcegit`.

See: `sourcegit.desktop`
```
[Desktop Entry]
Name=SourceGit
Comment=Open-source & Free Git GUI Client
Exec=/usr/bin/sourcegit
Icon=/usr/share/icons/sourcegit.png
Terminal=false
Type=Application
Categories=Development
MimeType=inode/directory;
```

**Comment by BrodyB** [comment]
It is with great sorrow and a heavy heart that I must inform you that I am still getting this bug in version 2025.28.

I am using the AMD64 AppImage under Fedora SilverBlue. Every time I fetch, pull, or push, I'm prompted to input the password for my SSH key ~6 times. I'm going to revert back to 2025.25 for now, which doesn't have this behavior.

**Comment by love-linger** [comment]
> I'm going to revert back to 2025.25 for now, which doesn't have this behavior.

Strange.

**Comment by piotr-fraczek** [comment]
Unfortunately, on linux manjaro problem still exists

**Comment by love-linger** [comment]
Try to launch `SourceGit` from terminal and call ```eval `ssh-agent -s` ``` first before that

**Comment by piotr-fraczek** [comment]
> Try to launch `SourceGit` from terminal and call `` eval `ssh-agent -s` `` first before that

like this?
```
➜  ~ eval `ssh-agent -s`                                                                  
Agent pid 7729
➜  ~ sourcegit 
```

prompting for password every time

-- edit --

but if I add manual key

```
➜  ~ ssh-add ~/.ssh/id_ed25519 
Enter passphrase for /home/piofra/.ssh/id_ed25519: 
Identity added: /home/piofra/.ssh/id_ed25519 (PioFra-ed25519)
➜  ~ sourcegit 
```

SourceGit don't want password, and git command working ok

**Comment by BrodyB** [comment]
> but if I add manual key, SourceGit don't want password, and git command working ok

I'm seeing the same thing as Piotr **_except_** that manually re-adding my SSH key to ssh-agent has no effect.

**Comment by OldSneerJaw** [comment]
I ran into this issue today only after upgrading to 2025.28 and 2025.29. Running `ssh-add` to re-add my private key didn't help.

However, I just downgraded to 2025.27 and it is back to normal (i.e. not asking for my SSH keyfile password for each action). I'm on Pop!_OS 22.04 LTS.

**Comment by love-linger** [comment]
I've reverted the changes since 2025.27

**Comment by Akira-Kuru** [comment]
Sorry for not coming back on this.
The error has been persistent and I went from 2025.26 to 27, 28 and now 29.

On the latest version it still happens but doesn't happen when running over the terminal.

This was already the case on version 2025.26.

I was contemplating if this has to do since I am using zsh and not bash.
However, I switched to bash on different Terminal (Konsole, Kitty and Ghostty) I could still pull and push without putting in a password.

Not sure what else I can try to make SourceGit work.

Currently running 2025.29 over AppImage.

**Comment by ozmium** [comment]
I'm seeing the same problem in the latest version of SourceGit 2025.29 on Ubuntu Linux 22.04.5 LTS. Every time I do a Git Fetch, it keeps asking me for the SSH password.

<img width="381" height="166" alt="SourceGit Askpass SSH password prompt" src="https://github.com/user-attachments/assets/eb206a33-83a9-445c-bc21-fe10447154f8" />

But when I run `git fetch` in a Terminal, I do not get this problem. On the Terminal, it only asks for the password once, after I restart the computer, and then it is saved somewhere so that I don't have to keep retyping it.

This problem did not happen in older versions of SourceGit, like `sourcegit-2025.14.linux.amd64.AppImage` and `sourcegit-2025.25.linux.amd64.AppImage`

**Comment by love-linger** [comment]
@ozmium Could you help me test the latest CI build from Github Action? I have rolled back the relevant code to `2025.14`.

https://github.com/sourcegit-scm/sourcegit/actions/runs/16932437575

**Comment by piotr-fraczek** [comment]
@love-linger if you need any tests, I'll be happy to help you. also I can take a look at the code and try see what the problem is.

**Comment by love-linger** [comment]
@piotr-fraczek Thank you very much. You can download and test the latest CI build from Github Action. https://github.com/sourcegit-scm/sourcegit/actions/runs/16932437575

**Comment by love-linger** [comment]
The source code about SSH settings in git command is https://github.com/sourcegit-scm/sourcegit/blob/e87eb8137bc043e0ca8568ce003fe22c4416dcb1/src/Commands/Command.cs#L175-L187

**Comment by ozmium** [comment]
@love-linger I can try to help with the testing, but could you please also fix this issue?

* https://github.com/sourcegit-scm/sourcegit/issues/1725

Please try to add it into the CI build.

**Comment by ozmium** [comment]
By the way, when I download the SourceGit AppImage on Ubuntu Linux, I always make my own Desktop Icon Launcher, with settings like this:

`/home/username/.local/share/applications/SourceGit.desktop`

```properties
[Desktop Entry]
Type=Application
Encoding=UTF-8
Name=SourceGit
Icon=/home/username/Apps/SourceGit.icns
Comment=Source Git Client
#Exec=/home/username/Apps/sourcegit-2025.14.linux.amd64.AppImage
Exec=/home/username/Apps/sourcegit-2025.29.linux.amd64.AppImage
Terminal=false
Type=Application
Categories=GNOME;Application;Development;
#StartupNotify=true
```

I don't know if this is causing the bug or not.

I use these guides:

* https://dev.to/duhoang/ubuntu-create-postman-shortcut-31jp
* https://askubuntu.com/questions/1026528/adding-custom-programs-to-favourites-of-ubuntu-dock

**Comment by piotr-fraczek** [comment]
> [@piotr-fraczek](https://github.com/piotr-fraczek) Thank you very much. You can download and test the latest CI build from Github Action. https://github.com/sourcegit-scm/sourcegit/actions/runs/16932437575

@love-linger nothing changed, dialog for password every time
I'll try prepare local env from source and debug this issue

**Comment by BrodyB** [comment]
> I've reverted the changes since 2025.27

Confirming that `2025.30` does not have the AskPass spam bug (using the amd64 AppImage in Bazzite/Fedora) :v:

**Comment by love-linger** [comment]
> Confirming that 2025.30 does not have the AskPass spam bug (using the amd64 AppImage in Bazzite/Fedora)

@BrodyB Did you download the package for `Releases` or the latest package in `GitHub Action`?

**Comment by BrodyB** [comment]
> [@BrodyB](https://github.com/BrodyB) Did you download the package for `Releases` or the latest package in `GitHub Action`?

In my case, this is the Release package.

**Comment by Akira-Kuru** [comment]
I just tried it myself over AppImage on Archlinux and it still happens for me.
I just did a simple pull on my branch and it pops up.

**Comment by vysocoqite** [comment]
Hello.
OS: Linux Fedora 42.
SourceGit: 2025.31.
Git: 2.51.

I tried to research.

1) Execute in terminal `ssh-add` and input passphrase.
  * Terminal opened: works without passphrase in terminal and SourceGit.
  * Terminal closed: works without passphrase in terminal and SourceGit.
  * Logout: works without passphrase in terminal and SourceGit.
  * Reboot: asks passphrase.

2) Execute `fetch` in SourceGit and input passphrase.
  * try again `fetch` in SourceGit: asks passphrase.
  * open terminal and try `fetch`: asks passphrase.
  * open terminal and execute `ssh-add`: works as in point 1.

3) execute point 1 then `eval "$(ssh-agent -s)"`.
  * gets `permission denied (publickey)` in terminal and SourceGit asks passphrase

Looks like SourceGit do latter. It uses data if `ssh-add` executed through terminal. But doesn't use this data if it do itself. Or it does `ssh-agent ssh-add`, then before next action again `ssh-agent  ssh-add`.

I don't use `.ssh/config`, SSH-managers/vallets, zsh-plugins.

**Comment by ghost** [comment]
OS: Linux Fedora 42, KDE Plasma 6.4.4.
SourceGit: 2025.32.
Git: 2.51.
SSH: OpenSSH_9.9p1.
Terminal: zsh.

Hello. I did research and it works strange.

* After reboot, I press `fetch` in `SourceGit`.
     * rpm version asks password.
     * souce code version lauched in `VS Code` with `run and debug` displays `Permission denied (publickey)`.
* Then I execute `ssh-add` in terminal and press `fetch` in `SourceGit`.
     * rpm version asks password.
     * source code version doesn't ask.

I don't use `.ssh/config`, SSH-managers/vallets, zsh ssh-plugins.

**Comment by love-linger** [comment]
I've no idea how to deal with this. Different users have reported different situations, and sometimes they are exactly opposite. What can be confirmed at present is that this issue behaves differently on different Linux distributions (this issue does not exist on Windows and macOS platforms).

If anyone has a solution to this problem, please feel free to submit a PR.

**Comment by Doodeletion** [comment]
Is it possible to have SourceGit not do any extra work related to SSH keys (as a new option)? 
I use the FIDO SSH key types (ecdsa-sk / ed25519-s). My operating system prompts me to unlock my FIDO key.
Everything works fine when I use the command line. In SourceGit I get the Askpass popup in addition to the operating system popup.

If I ~~uncomment~~ comment these lines it works.
https://github.com/sourcegit-scm/sourcegit/blob/080c446ce0b24edb437dbdddd515402a0a364b0d/src/Commands/Command.cs#L176C13-L184C95

----
Something else:  
While looking through the SourceCode I noticed that `credential.helper` seems to always be set to `manager`. Why is that?

https://github.com/sourcegit-scm/sourcegit/blob/080c446ce0b24edb437dbdddd515402a0a364b0d/src/Commands/Command.cs#L193C1-L197C30

**Comment by love-linger** [comment]
> Is it possible to have SourceGit not do any extra work related to SSH keys (as a new option)?

`SourceGit` use these ENV to make sure there's a GUI-based ask-pass tool. It is the common way that used by many clients, such as `GitHub Desktop`, `GitExtensions`, `VSCode` etc.

> While looking through the SourceCode I noticed that credential.helper seems to always be set to manager. Why is that?

- This setting is only used for account authentication between `git` and the hosting platform, and is completely unrelated to this issue. The `ssh` process does not use this setting.
- The reason is basically the same as the previous question. `SourceGit` needs to ensure that there is a GUI-based tool. For the Linux platform, we provide two options: `git-credential-manager` or `git-credential-libsecret`

**Comment by love-linger** [comment]
And this issue only exists on Linux platform. I do not know why.

**Comment by Doodeletion** [comment]
> SourceGit use these ENV to make sure there's a GUI-based ask-pass tool. It is the common way that used by many clients, such as GitHub Desktop, GitExtensions, VSCode etc.

Thanks, that makes sense. 

For my specific use case, my operating system handles spawning a GUI. If you could add an option that skips the SSH setup, it would be very helpful to me. 🙏 
I have tested that disabling these lines would work for my machine.
https://github.com/sourcegit-scm/sourcegit/blob/080c446ce0b24edb437dbdddd515402a0a364b0d/src/Commands/Command.cs#L176C13-L184C95

**Comment by love-linger** [comment]
> I have tested that disabling these lines would work for my machine.

@Doodeletion If that fixes this issue for you, you can try to clear the private key in `Edit Remote` popup.

<img width="1328" height="546" alt="Image" src="https://github.com/user-attachments/assets/fd51fbf9-e437-4cd0-9c2a-68bfab2df726" />
