### ISSUE TITLE
[Bug] Extra whitespace between lines in DiffView when Show Hidden Symbols is enabled

### ISSUE THREAD

**Issue by gadfly3173** [sourcegit-scm/sourcegit#364]
![image](https://github.com/user-attachments/assets/66825328-3aa9-47c7-97a1-78168e3e6f12)

reproduce patch:
```diff
diff --git a/README.md b/README.md
index 50d7525..60ab343 100644
--- a/README.md
+++ b/README.md
@@ -3,8 +3,12 @@
 Opensource Git GUI client.
 
 ## Highlights
 
+
+			}
+					}});
+			}
 * Supports Windows/macOS/Linux
 * Opensource/Free
 * Fast
 * English/German/Português/简体中文/繁體中文

```

**Comment by love-linger** [comment]
I don't understand, did you mean this line?
![image](https://github.com/user-attachments/assets/c0107500-c527-4410-9eab-595ec8f57f13)

**Comment by gadfly3173** [comment]
yes, after disabled Show Hidden Symbols , it will work fine.
![image](https://github.com/user-attachments/assets/917b6a5e-b7d2-4b3d-ac61-12fdd1a1eb64)

**Comment by love-linger** [comment]
I think this is just a issue about layout rounding in Avaloina.

**Comment by love-linger** [comment]
for example, after i move the window from a screen to anthor which has different UI scaling:

![image](https://github.com/user-attachments/assets/54775a13-7c4c-445e-bf60-4a085fc20b8f)

**Comment by gadfly3173** [comment]
But for me, lines indented with tabs will be very noticeably offset, whereas lines indented with spaces or with hidden symbols turned off will not have this problem.

![image](https://github.com/user-attachments/assets/0c8ce651-6b56-4f66-b9cd-523cd54760e1)

![image](https://github.com/user-attachments/assets/95a4e744-6d66-4947-9161-e9fd4667dc94)

**Comment by love-linger** [comment]
Try to change the monospace font to built-in `JetBrains Mono`?

**Comment by gadfly3173** [comment]
> Try to change the monospace font to built-in `JetBrains Mono`?

`JetBrains Mono` works fine, but others like `Dejavu` / `Consolas` / `FreeMono` all have this issue

**Comment by love-linger** [comment]
I've pushed a commit 9f39a9b2951010634c6b43ab06a721a35bdc28a3 that try to solve this problem.

**Comment by gadfly3173** [comment]
Although the spacing between the lines is still there, the effect looks good after the background color is filled.

**Comment by love-linger** [comment]
ed7465def5 - enhance: render highlight background manually instead of using `TextRunProperties.SetBackgroundBrush(IBrush)`

**Comment by gadfly3173** [comment]
> [ed7465d](https://github.com/sourcegit-scm/sourcegit/commit/ed7465def5bd867cbeef3f73fcdd6f1fc79213db) - enhance: render highlight background manually instead of using `TextRunProperties.SetBackgroundBrush(IBrush)`

![image](https://github.com/user-attachments/assets/4822313d-cf8a-438d-86c3-c91b09c9d5d5)

The offset still exists, and I think it is acceptable not to fix the current effect.
